### ISSUE TITLE
Can't preview URLs

### ISSUE THREAD

**Issue by ta1bbty** [cablej/FileChangeMonitor#3]
I get this error when I try to preview JS on my private instance : 

```
POST /api/domains/previewJSUrls 500 4.348 ms - -
Error [ERR_SOCKET_CLOSED]: Socket is closed
    at Socket._writeGeneric (net.js:707:18)
    at Socket._write (net.js:729:8)
    at doWrite (_stream_writable.js:410:12)
    at clearBuffer (_stream_writable.js:540:7)
    at Socket.Writable.uncork (_stream_writable.js:314:7)
    at ClientRequest._flushOutput (_http_outgoing.js:801:10)
    at ClientRequest._flush (_http_outgoing.js:776:16)
    at ClientRequest._deferToConnect (_http_client.js:268:47)
    at callSocketMethod (_http_client.js:711:7)
    at ClientRequest.onSocket (_http_client.js:716:7)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:187:15)
    at ClientRequest.EventEmitter.emit (domain.js:441:20)
    at tickOnSocket (_http_client.js:655:7)
    at onSocketNT (_http_client.js:694:5)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by cablej** [comment]
Hi @ta1bbty,

Thank you for the feedback. This looks to be due to an error in the (now-unmaintained) paranoid-request module by Uber not supporting the latest Node version. I've incorporated the changes from the pull request at https://github.com/evert/paranoid-request/tree/normalize-args and it now seems to be working again. You can fix by running `npm install`, and if that doesn't work, deleting `node_modules/paranoid-request` and installing again. Let me know if you run into any other issues.

Thanks,
Jack

**Comment by jaikishantulswani** [comment]
@cablej  I am also not getting the preview  after adding domain and selecting particular js url's.
I also tried to remove `node_modules/paranoid-request` and installing npm install.

Thanks
![Screenshot from 2019-05-03 22-19-36](https://user-images.githubusercontent.com/30144126/57152750-f36c0780-6df1-11e9-94c5-bfc5594e5ce2.png)
